### ISSUE TITLE
📌 Tracker: Missing and To-Be-Added CLI Commands

### ISSUE THREAD

**Issue by bupd** [goharbor/harbor-cli#94]
## Objective: 
Track the missing commands in the CLI and ensure their implementation.
Current focus is to add more commands which includes.

1. immutability tag rules
2. set quotas
3. set replication policies
4. create retention policies
5. vulnerability scanning policy 
6. webhooks

and more commands mentioned below.

### 🚧 Missing Commands

| Command         | Description                       | Priority | Status |
| --------------- | --------------------------------- | -------- | ------ |
| **Member**       | Manage project Members             | High     | #85   |
| **Quota**       | Manage project quotas             | High     | #97   |
| **Robot**       | Manage robot accounts in projects | High     | #100  |
| **Replication** | Manage replication policies       | High     | done  |
| **Retention**   | Manage retention policies         | High     | done  |
| **Ping**        | Ping the API server               | Low      | done  |
| **Webhook**       | Manage project webhooks     | Medium | done  |
| **Security**      | Manage system security settings  | Medium | done  |
| **Configuration** | Manage system configurations | Medium | done  |
| **System Config** | Manage internal system configurations | Medium | done | 
| **Audit**       | Manage and audit recent logs      | Medium   | to-do  |
| **Usergroup**   | Manage user groups                | Medium   | to-do  |

---

### 🛠️ Commands to Handle After Initial Implementation

| Command           | Description                   |
| ----------------- | ------------------------------------- |
| **LDAP**          | Integrate with LDAP   |
| **Preheat**       | Manage preheat policies and instances |
| **Permissions**   | Manage system and project permissions |

---

### 📝 Implementation Steps

   - [x] Implement Member command.
   - [x] Implement Quota command.
   - [x] Implement Robot command.
   - [x] Implement Audit command.
   - [x] Ping
   - [x] Implement Replication command.
   - [x] Webhook
   - [x] Security
   - [x] Configuration (ongoing)
   - [x] System Config (ongoing)
   - [x] LDAP
   - [ ] Implement Retention command. ([ongoing #364](https://github.com/goharbor/harbor-cli/pull/364))
   - [ ] Implement Usergroup command.
   - [ ] Preheat
   - [ ] Permissions
   - [ ] Add Unit, End to end tests for the commands.

---

### 📌 Issue Tracking and Progress

- Create individual GitHub issues for each command implementation.
- Reference this master issue in each individual issue to maintain a coherent structure and clear dependencies.

---

### 👤 Personal Note

I would like to tackle these issues to ensure proper implementation and integration of each command. 

Your feedback and suggestions are welcome as I work through this.

Edit:
> This issue is meant for collaboration and streamlining the process for everyone. Everyone is welcome to contribute and work on this. This issue serves as a tracker and reference point for all the missing commands in the CLI.

Last Updated: 09/Sep/25

**Comment by bishal7679** [comment]
Hello @bupd it's really awesome that you created a tracker which would definitely help all of us. But as per your personal note wouldn't it be better to give chance to everyone like they would create one issue by referring this tracker one. And only one person will get assigned and work for a particular issue at a time, which wouldn't create such a conflict like two people working for a same issue and anyone of them raised PR before one
WDYT???

**Comment by bupd** [comment]
Thanks @bishal7679 .  I want to clarify that the main reason I created this issue is to serve as a tracker for all the missing commands in the CLI and to be referred to as a parent issue where we can track progress collectively. This issue is meant for collaboration and streamlining the process for everyone involved.

Everyone is welcome to work on this. This is an open-source project, and I did not mean to imply that I am the only one allowed to work on these issues. My goal is to ensure proper implementation and integration, and I encourage and welcome contributions from everyone. Feel free to reference this issue and create your own issues to work on specific commands.

Let's work together to make this project better!

**Comment by bishal7679** [comment]
> Thanks @bishal7679 . I want to clarify that the main reason I created this issue is to serve as a tracker for all the missing commands in the CLI and to be referred to as a parent issue where we can track progress collectively. This issue is meant for collaboration and streamlining the process for everyone involved.
> 
> Everyone is welcome to work on this. This is an open-source project, and I did not mean to imply that I am the only one allowed to work on these issues. My goal is to ensure proper implementation and integration, and I encourage and welcome contributions from everyone. Feel free to reference this issue and create your own issues to work on specific commands.
> 
> Let's work together to make this project better!

Awesome :raised_hands:

**Comment by adwait-godbole** [comment]
Hi @bupd can you point out some `good first issues` ? I can't seem to find any label on the existing ones sadly :(

**Comment by rizul2108** [comment]
@bupd can i work on any of the above commands that has not been yet started ?

**Comment by bupd** [comment]
Sure

**Comment by LAKSHJAIN14** [comment]
Hey @bupd , I was looking to contribute to the CLI and noticed that the usergroup command has an active PR.
I see that the instance command (P2P preheat providers) is implemented, but the ability to manage Preheat Policies seems to be missing. I would like to work on implementing the preheat policy command group (list, create, update, delete, and execute) to complete this feature so should I open an issue for that or what or is there any other command I can work on ?
